// 自动生成文件，请勿手改。生成工具：tools/fieldname.py
// 数据来源：gamemd.exe 里各 TypeClass 的 `Read_INI` —— 键名两侧各出现一次
// 的字段访问给出 (偏移, 名字)。完整数据见 db/fieldnames.json，说明见 docs/fieldnames.md。
//
// 只收「双向」条目（缺省值与结果都落在同一个偏移上），以及没被人争过的单向条目。
// 单向 + 有争议 = 证据不够，一律不进本表。

#pragma once

#include <cstdint>
#include <cstring>

namespace ra2 {
namespace re {

struct FieldName {
    uint32_t off;
    const char* key;   // INI 键名（原样，大小写以文件为准）
    uint8_t width;     // 字段宽度，字节
    const char* type;  // int / bool / ?（? = 读取入口不在已认出的两个里）
};

struct ClassFieldNames {
    const char* cls;
    uint32_t count;
    const FieldName* fields;
};

inline constexpr FieldName kFN_BuildingTypeClass[] = {
    {0xE08, "BUILDCAT", 4, "?"},
    {0xE28, "GATECLOSEDELAY", 4, "?"},
    {0xE30, "LIGHTVISIBILITY", 4, "int"},
    {0xE34, "LIGHTINTENSITY", 4, "?"},
    {0xE38, "LIGHTREDTINT", 4, "?"},
    {0xE3C, "LIGHTGREENTINT", 4, "?"},
    {0xE40, "LIGHTBLUETINT", 4, "?"},
    {0xEB4, "ADJACENT", 4, "int"},
    {0xEB8, "FACTORY", 4, "?"},
    {0xEDC, "DEPLOYFACING", 4, "int"},
    {0xEF0, "FOUNDATION", 4, "?"},
    {0xEF4, "HEIGHT", 4, "int"},
    {0xF1C, "ANIMACTIVE", 4, "?"},
    {0xF48, "ACTIVEANIMGARRISONED", 4, "?"},
    {0x1050, "ACTIVEANIMZADJUST", 4, "int"},
    {0x1054, "ACTIVEANIMYSORT", 4, "int"},
    {0x1058, "ACTIVEANIMPOWERED", 1, "bool"},
    {0x1059, "ACTIVEANIMPOWEREDLIGHT", 1, "bool"},
    {0x105A, "ACTIVEANIMTWODAMAGED", 1, "?"},
    {0x105B, "ACTIVEANIMPOWEREDSPECIAL", 1, "bool"},
    {0x1094, "ACTIVEANIMTWOZADJUST", 4, "int"},
    {0x1098, "ACTIVEANIMTWOYSORT", 4, "int"},
    {0x109C, "ACTIVEANIMTWOPOWERED", 1, "bool"},
    {0x109D, "ACTIVEANIMTHREE", 1, "?"},
    {0x109E, "ACTIVEANIMTHREEDAMAGED", 1, "?"},
    {0x10D8, "ACTIVEANIMTHREEZADJUST", 4, "int"},
    {0x10DC, "ACTIVEANIMTHREEYSORT", 4, "int"},
    {0x10E0, "ACTIVEANIMTHREEPOWERED", 1, "bool"},
    {0x10E1, "ACTIVEANIMFOUR", 1, "?"},
    {0x10E2, "ACTIVEANIMFOURDAMAGED", 1, "?"},
    {0x111C, "ACTIVEANIMFOURZADJUST", 4, "int"},
    {0x1120, "ACTIVEANIMFOURYSORT", 4, "int"},
    {0x1125, "SUPERANIM", 1, "?"},
    {0x1126, "SUPERANIMDAMAGED", 1, "?"},
    {0x115C, "TURRETANIM", 4, "?"},
    {0x11A0, "IDLEANIM", 4, "?"},
    {0x11A4, "PRODUCTIONANIMZADJUST", 4, "int"},
    {0x11A8, "PRODUCTIONANIMYSORT", 4, "int"},
    {0x11E0, "TURRETANIMX", 4, "int"},
    {0x11E4, "TURRETANIMY", 4, "int"},
    {0x11E8, "TURRETANIMZADJUST", 4, "int"},
    {0x122C, "SPECIALANIMZADJUST", 4, "int"},
    {0x1230, "SPECIALANIMYSORT", 4, "int"},
    {0x1234, "SPECIALANIMPOWERED", 1, "bool"},
    {0x1235, "SPECIALANIMPOWEREDLIGHT", 1, "bool"},
    {0x1236, "SPECIALANIMTWODAMAGED", 1, "?"},
    {0x1270, "SPECIALANIMTWOZADJUST", 4, "int"},
    {0x1274, "SPECIALANIMTWOYSORT", 4, "int"},
    {0x1279, "SPECIALANIMTHREE", 1, "?"},
    {0x127A, "SPECIALANIMTHREEDAMAGED", 1, "?"},
    {0x12B4, "SPECIALANIMTHREEZADJUST", 4, "int"},
    {0x12B8, "SPECIALANIMTHREEYSORT", 4, "int"},
    {0x12BD, "SPECIALANIMFOUR", 1, "?"},
    {0x12BE, "SPECIALANIMFOURDAMAGED", 1, "?"},
    {0x12F8, "SPECIALANIMFOURZADJUST", 4, "int"},
    {0x1301, "LOWPOWER", 1, "?"},
    {0x1302, "LOWPOWERDAMAGED", 1, "?"},
    {0x133C, "SUPERANIMZADJUST", 4, "int"},
    {0x1340, "SUPERANIMYSORT", 4, "int"},
    {0x1344, "SUPERANIMPOWERED", 1, "bool"},
    {0x1345, "SUPERANIMTWO", 1, "?"},
    {0x1346, "SUPERANIMTWODAMAGED", 1, "?"},
    {0x1380, "SUPERANIMTWOZADJUST", 4, "int"},
    {0x1384, "SUPERANIMTWOYSORT", 4, "int"},
    {0x1388, "SUPERANIMTWOPOWERED", 1, "bool"},
    {0x1389, "SUPERANIMTHREE", 1, "?"},
    {0x138A, "SUPERANIMTHREEDAMAGED", 1, "?"},
    {0x13C4, "SUPERANIMTHREEZADJUST", 4, "int"},
    {0x13C8, "SUPERANIMTHREEYSORT", 4, "int"},
    {0x13CC, "SUPERANIMTHREEPOWERED", 1, "bool"},
    {0x13CD, "SUPERANIMFOUR", 1, "?"},
    {0x13CE, "SUPERANIMTHREEPOWEREDEFFECT", 1, "bool"},
    {0x1408, "SUPERANIMFOURZADJUST", 4, "int"},
    {0x140C, "SUPERANIMFOURYSORT", 4, "int"},
    {0x1410, "SUPERANIMFOURPOWERED", 1, "bool"},
    {0x1411, "SPECIALANIM", 1, "?"},
    {0x1412, "SPECIALANIMDAMAGED", 1, "?"},
    {0x144C, "IDLEANIMZADJUST", 4, "int"},
    {0x1450, "IDLEANIMYSORT", 4, "int"},
    {0x1454, "IDLEANIMPOWERED", 1, "bool"},
    {0x1498, "LOWPOWERPOWERED", 1, "bool"},
    {0x1499, "SUPERLOWPOWER", 1, "?"},
    {0x149A, "SUPERLOWPOWERDAMAGED", 1, "?"},
    {0x14DC, "SUPERLOWPOWERPOWERED", 1, "bool"},
    {0x14DD, "PRODUCTIONANIM", 1, "?"},
    {0x14DE, "PRODUCTIONANIMDAMAGED", 1, "?"},
    {0x14E0, "UPGRADES", 4, "int"},
    {0x1524, "ANTIAIRVALUE", 4, "int"},
    {0x1528, "ANTIARMORVALUE", 4, "int"},
    {0x152C, "ANTIINFANTRYVALUE", 4, "int"},
    {0x154A, "TOGGLEPOWER", 1, "bool"},
    {0x154B, "HALFDAMAGESMOKELOCATION1", 1, "?"},
    {0x154C, "NOTWORKINGSOUND", 1, "?"},
    {0x154F, "BASENORMAL", 1, "bool"},
    {0x1550, "ELIGIBILEFORALLYBUILDING", 1, "bool"},
    {0x1551, "ELIGIBLEFORDELAYKILL", 1, "bool"},
    {0x1552, "NEEDSENGINEER", 1, "bool"},
    {0x1554, "CAPTUREEVAEVENT", 4, "?"},
    {0x1558, "PRODUCECASHSTARTUP", 4, "int"},
    {0x155C, "PRODUCECASHAMOUNT", 4, "int"},
    {0x1560, "PRODUCECASHDELAY", 4, "int"},
    {0x1564, "INFANTRYGAINSELFHEAL", 4, "int"},
    {0x1568, "UNITSGAINSELFHEAL", 4, "int"},
    {0x156C, "REFINERYSMOKEFRAMES", 4, "int"},
    {0x1570, "BIB", 1, "bool"},
    {0x1571, "WALL", 1, "bool"},
    {0x1572, "CAPTURABLE", 1, "bool"},
    {0x1573, "POWERED", 1, "bool"},
    {0x1574, "POWEREDSPECIAL", 1, "bool"},
    {0x1575, "OVERPOWERABLE", 1, "bool"},
    {0x1576, "SPYABLE", 1, "bool"},
    {0x1577, "CANC4", 1, "bool"},
    {0x1579, "UNSELLABLE", 1, "bool"},
    {0x157A, "CLICKREPAIRABLE", 1, "bool"},
    {0x157B, "CANBEOCCUPIED", 1, "bool"},
    {0x157C, "CANOCCUPYFIRE", 1, "bool"},
    {0x1580, "MAXNUMBEROCCUPANTS", 4, "int"},
    {0x1620, "NUMBERIMPASSABLEROWS", 4, "int"},
    {0x16A4, "RADAR", 1, "bool"},
    {0x16A5, "SPYSAT", 1, "bool"},
    {0x16A7, "ISANIMDELAYEDFIRE", 1, "bool"},
    {0x16A9, "UNITREPAIR", 1, "bool"},
    {0x16AA, "UNITRELOAD", 1, "bool"},
    {0x16AB, "BUNKER", 1, "bool"},
    {0x16AC, "CLONING", 1, "bool"},
    {0x16AD, "GRINDING", 1, "bool"},
    {0x16AE, "UNITABSORB", 1, "bool"},
    {0x16AF, "INFANTRYABSORB", 1, "bool"},
    {0x16B0, "SECRETLAB", 1, "bool"},
    {0x16B1, "DOUBLETHICK", 1, "bool"},
    {0x16B2, "FLAT", 1, "bool"},
    {0x16B3, "DOCKUNLOAD", 1, "bool"},
    {0x16B4, "RECOILLESS", 1, "bool"},
    {0x16B5, "HASSTUPIDGUARDMODE", 1, "bool"},
    {0x16B6, "BRIDGEREPAIRHUT", 1, "bool"},
    {0x16B7, "GATE", 1, "bool"},
    {0x16B9, "CONSTRUCTIONYARD", 1, "bool"},
    {0x16BA, "NUKESILO", 1, "bool"},
    {0x16BB, "REFINERY", 1, "bool"},
    {0x16BD, "WEAPONSFACTORY", 1, "bool"},
    {0x16C1, "HOSPITAL", 1, "bool"},
    {0x16C4, "CHARGEDANIMTIME", 1, "?"},
    {0x16C5, "TURRETANIMISVOXEL", 1, "bool"},
    {0x16C8, "SENSORARRAY", 1, "bool"},
    {0x16CB, "HELIPAD", 1, "bool"},
    {0x16CC, "OREPURIFIER", 1, "bool"},
    {0x16CD, "FACTORYPLANT", 1, "bool"},
    {0x16E4, "GDIBARRACKS", 1, "bool"},
    {0x16E5, "NODBARRACKS", 1, "bool"},
    {0x16E6, "YURIBARRACKS", 1, "bool"},
    {0x16EC, "DELAYEDFIREDELAY", 4, "int"},
    {0x16F0, "SUPERWEAPON", 4, "?"},
    {0x16F8, "GATESTAGES", 4, "int"},
    {0x1701, "INVISIBLEINGAME", 1, "bool"},
    {0x1702, "TERRAINPALETTE", 1, "bool"},
    {0x1703, "PLACEANYWHERE", 1, "bool"},
    {0x1704, "EXTRADAMAGESTAGE", 1, "bool"},
    {0x1705, "AIBUILDTHIS", 1, "bool"},
    {0x1706, "ISBASEDEFENSE", 1, "bool"},
    {0x1708, "CONCENTRICRADIALINDICATOR", 1, "bool"},
    {0x170C, "PSYCHICDETECTIONRADIUS", 4, "int"},
    {0x1764, "PRIMARYFIREDUALOFFSET", 1, "bool"},
    {0x1765, "PROTECTWITHWALL", 1, "bool"},
    {0x1766, "CANHIDETHINGS", 1, "bool"},
    {0x1767, "CRATEBENEATH", 1, "bool"},
    {0x1768, "LEAVERUBBLE", 1, "bool"},
    {0x1769, "CRATEBENEATHISMONEY", 1, "bool"},
    {0x1780, "NUMBEROFDOCKS", 4, "int"},
};
inline constexpr FieldName kFN_InfantryTypeClass[] = {
    {0xDFC, "PIP", 4, "?"},
    {0xE40, "FIREUP", 4, "int"},
    {0xE48, "SECONDARYFIRE", 4, "int"},
    {0xEAD, "NOTHUMAN", 1, "bool"},
    {0xEAE, "IVAN", 1, "bool"},
    {0xEB4, "OCCUPIER", 1, "bool"},
    {0xEB5, "ASSAULTER", 1, "bool"},
    {0xEB8, "HARVESTRATE", 4, "int"},
    {0xEBC, "FEARLESS", 1, "bool"},
    {0xEBD, "CRAWLS", 1, "bool"},
    {0xEBE, "INFILTRATE", 1, "bool"},
    {0xEBF, "FRAIDYCAT", 1, "bool"},
    {0xEC0, "TIBERIUMPROOF", 1, "bool"},
    {0xEC1, "CIVILIAN", 1, "bool"},
    {0xEC3, "ENGINEER", 1, "bool"},
    {0xEC4, "AGENT", 1, "bool"},
    {0xEC8, "DEPLOYER", 1, "bool"},
    {0xEC9, "DEPLOYEDCRUSHABLE", 1, "bool"},
    {0xECA, "USEOWNNAME", 1, "bool"},
    {0xECB, "JUMPJETTURN", 1, "bool"},
};
inline constexpr FieldName kFN_ObjectTypeClass[] = {
    {0x9C, "ARMOR", 4, "?"},
    {0xA0, "STRENGTH", 4, "int"},
    {0x1E8, "NOSPAWNALT", 1, "bool"},
    {0x211, "ALTERNATEARCTICART", 1, "bool"},
    {0x22C, "THEATER", 1, "bool"},
    {0x22D, "CRUSHABLE", 1, "bool"},
    {0x22E, "BOMBABLE", 1, "bool"},
    {0x22F, "RADARINVISIBLE", 1, "bool"},
    {0x230, "SELECTABLE", 1, "bool"},
    {0x231, "LEGALTARGET", 1, "bool"},
    {0x232, "INSIGNIFICANT", 1, "bool"},
    {0x233, "IMMUNE", 1, "bool"},
    {0x236, "VOXEL", 1, "bool"},
    {0x237, "NEWTHEATER", 1, "bool"},
    {0x238, "HASRADIALINDICATOR", 1, "bool"},
};
inline constexpr FieldName kFN_TechnoTypeClass[] = {
    {0x294, "WALKRATE", 4, "int"},
    {0x298, "IDLERATE", 4, "int"},
    {0x2C0, "SPECIALTHREATVALUE", 4, "?"},
    {0x2F0, "THREATAVOIDANCECOEFFICIENT", 4, "?"},
    {0x300, "DEACCELERATIONFACTOR", 4, "?"},
    {0x308, "ACCELERATIONFACTOR", 4, "?"},
    {0x310, "CLOAKINGSPEED", 4, "int"},
    {0x370, "WEIGHT", 4, "?"},
    {0x378, "PHYSICALSIZE", 4, "?"},
    {0x380, "SIZE", 4, "?"},
    {0x388, "SIZELIMIT", 4, "?"},
    {0x390, "HOVERATTACK", 1, "bool"},
    {0x394, "VHPSCAN", 4, "?"},
    {0x3B8, "BUILDLIMIT", 4, "int"},
    {0x3C8, "DEPLOYTIME", 4, "?"},
    {0x3D0, "FIREANGLE", 4, "?"},
    {0x3D4, "PIPSCALE", 4, "?"},
    {0x3D8, "PIPSDRAWFORALL", 1, "bool"},
    {0x3E0, "PIXELSELECTIONBRACKETDELTA", 4, "int"},
    {0x410, "POWEREDUNIT", 1, "bool"},
    {0x5B4, "MOVEMENTZONE", 4, "?"},
    {0x5B8, "GUARDRANGE", 4, "?"},
    {0x5BC, "MAXDEBRIS", 4, "int"},
    {0x5C0, "MINDEBRIS", 4, "int"},
    {0x5E0, "PASSENGERS", 4, "?"},
    {0x5E4, "OPENTOPPED", 1, "bool"},
    {0x5E8, "SIGHT", 4, "int"},
    {0x5EC, "RESOURCEGATHERER", 1, "bool"},
    {0x5ED, "RESOURCEDESTINATION", 1, "bool"},
    {0x5EE, "REVEALTOALL", 1, "bool"},
    {0x5EF, "DRAINABLE", 1, "bool"},
    {0x5F0, "SENSORSSIGHT", 4, "int"},
    {0x5F4, "DETECTDISGUISERANGE", 4, "int"},
    {0x5F8, "BOMBSIGHT", 4, "int"},
    {0x5FC, "LEADERSHIPRATING", 4, "int"},
    {0x600, "NAVALTARGETING", 4, "int"},
    {0x604, "LANDTARGETING", 4, "int"},
    {0x60C, "BUILDTIMEMULTIPLIER", 4, "?"},
    {0x610, "COST", 4, "int"},
    {0x614, "SOYLENT", 4, "int"},
    {0x61C, "AIRSTRIKETEAM", 4, "int"},
    {0x62C, "AIRSTRIKERECHARGETIME", 4, "int"},
    {0x634, "TECHLEVEL", 4, "int"},
    {0x670, "THREATPOSED", 4, "int"},
    {0x67C, "SPEEDTYPE", 4, "?"},
    {0x684, "AMMO", 4, "int"},
    {0x688, "IFVMODE", 4, "int"},
    {0x68C, "AIRRANGEBONUS", 4, "?"},
    {0x690, "BERSERKFRIENDLY", 1, "bool"},
    {0x693, "NATURAL", 1, "bool"},
    {0x694, "UNNATURAL", 1, "bool"},
    {0x695, "CLOSERANGE", 1, "bool"},
    {0x6A4, "RADIALFIRESEGMENTS", 4, "int"},
    {0x6AC, "DEPLOYFIRE", 1, "bool"},
    {0x6AD, "DEPLOYTOLAND", 1, "bool"},
    {0x6AF, "OPPORTUNITYFIRE", 1, "bool"},
    {0x6B0, "DISTRIBUTEDFIRE", 1, "bool"},
    {0x6C1, "ATTACKCURSORONFRIENDLIES", 1, "?"},
    {0x6C4, "UNDEPLOYDELAY", 4, "?"},
    {0x6C8, "PREVENTATTACKMOVE", 1, "bool"},
    {0x6CC, "OWNER", 4, "?"},
    {0x6D0, "AIBASEPLANNINGSIDE", 4, "int"},
    {0x6D4, "STUPIDHUNT", 1, "?"},
    {0x6D5, "ALLOWEDTOSTARTINMULTIPLAYER", 1, "?"},
    {0x71C, "ROT", 4, "?"},
    {0x720, "TURRETOFFSET", 4, "?"},
    {0x724, "CANBEHIDDEN", 1, "bool"},
    {0x728, "POINTS", 4, "int"},
    {0x7FC, "SHADOWINDEX", 4, "?"},
    {0x800, "STORAGE", 4, "int"},
    {0x805, "GUNNER", 1, "bool"},
    {0x806, "HASTURRETTOOLTIPS", 1, "bool"},
    {0x808, "TURRETCOUNT", 4, "int"},
    {0x80C, "WEAPONCOUNT", 4, "int"},
    {0x810, "ISCHARGETURRET", 1, "bool"},
    {0x8A8, "PBARRELLENGTH", 4, "?"},
    {0x8AC, "PBARRELTHICKNESS", 4, "?"},
    {0xC8C, "TYPEIMMUNE", 1, "bool"},
    {0xC8D, "MOVETOSHROUD", 1, "bool"},
    {0xC8E, "TRAINABLE", 1, "bool"},
    {0xC90, "TARGETLASER", 1, "?"},
    {0xC91, "IMMUNETOVEINS", 1, "?"},
    {0xC95, "PITCHANGLE", 1, "?"},
    {0xC96, "TOPROTECT", 1, "?"},
    {0xC99, "DEATHWEAPON", 1, "?"},
    {0xC9B, "RADARVISIBLE", 1, "?"},
    {0xC9D, "SENSORS", 1, "bool"},
    {0xC9E, "NOMINAL", 1, "bool"},
    {0xC9F, "DONTSCORE", 1, "bool"},
    {0xCA0, "DAMAGESELF", 1, "bool"},
    {0xCCC, "REPAIRABLE", 1, "bool"},
    {0xCCD, "CREWED", 1, "bool"},
    {0xCCE, "NAVAL", 1, "bool"},
    {0xCCF, "REMAPABLE", 1, "?"},
    {0xCD0, "CLOAKABLE", 1, "bool"},
    {0xCD1, "GAPGENERATOR", 1, "bool"},
    {0xCD2, "GAPRADIUSINCELLS", 1, "int"},
    {0xCD3, "SUPERGAPRADIUSINCELLS", 1, "int"},
    {0xCD4, "TELEPORTER", 1, "bool"},
    {0xCD5, "ISGATTLING", 1, "bool"},
    {0xCD8, "WEAPONSTAGES", 4, "int"},
    {0xD0C, "RATEUP", 4, "int"},
    {0xD10, "RATEDOWN", 4, "int"},
    {0xD14, "SELFHEALING", 1, "?"},
    {0xD15, "EXPLODES", 1, "bool"},
    {0xD18, "DEBRISMAXIMUMS", 4, "?"},
    {0xD21, "TURRETSPINS", 1, "bool"},
    {0xD22, "TILTCRASHJUMPJET", 1, "bool"},
    {0xD23, "NORMALIZED", 1, "?"},
    {0xD28, "CRUSHER", 1, "?"},
    {0xD29, "OMNICRUSHER", 1, "?"},
    {0xD2A, "OMNICRUSHRESISTANT", 1, "?"},
    {0xD2D, "AUTOCRUSH", 1, "?"},
    {0xD2E, "BUNKERABLE", 1, "?"},
    {0xD2F, "CANDISGUISE", 1, "bool"},
    {0xD30, "PERMADISGUISE", 1, "bool"},
    {0xD31, "DETECTDISGUISE", 1, "bool"},
    {0xD32, "DISGUISEWHENSTILL", 1, "bool"},
    {0xD33, "CANAPPROACHTARGET", 1, "bool"},
    {0xD35, "IMMUNETOPSIONICS", 1, "?"},
    {0xD36, "IMMUNETOPSIONICWEAPONS", 1, "?"},
    {0xD37, "IMMUNETORADIATION", 1, "?"},
    {0xD38, "PARASITEABLE", 1, "?"},
    {0xD39, "DEFAULTTOGUARDAREA", 1, "?"},
    {0xD3B, "IMMUNETOPOISON", 1, "?"},
    {0xD3C, "RESELECTIFLIMBOED", 1, "bool"},
    {0xD3D, "REJOINTEAMIFLIMBOED", 1, "bool"},
    {0xD3E, "SLAVED", 1, "?"},
    {0xD40, "ENSLAVES", 4, "?"},
    {0xD44, "SLAVESNUMBER", 4, "?"},
    {0xD48, "SLAVEREGENRATE", 4, "?"},
    {0xD4C, "SLAVERELOADRATE", 4, "?"},
    {0xD50, "OPENTRANSPORTWEAPON", 4, "?"},
    {0xD54, "SPAWNED", 1, "?"},
    {0xD58, "SPAWNS", 4, "?"},
    {0xD5C, "SPAWNSNUMBER", 4, "?"},
    {0xD60, "SPAWNREGENRATE", 4, "?"},
    {0xD64, "SPAWNRELOADRATE", 4, "?"},
    {0xD68, "MISSILESPAWN", 1, "?"},
    {0xD69, "UNDERWATER", 1, "?"},
    {0xD6A, "BALLOONHOVER", 1, "?"},
    {0xD6C, "SUPPRESSIONTHRESHOLD", 4, "?"},
    {0xD70, "JUMPJETTURNRATE", 4, "?"},
    {0xD74, "JUMPJETSPEED", 4, "?"},
    {0xD80, "JUMPJETHEIGHT", 4, "?"},
    {0xD8C, "JUMPJETNOWOBBLES", 1, "?"},
    {0xD90, "JUMPJETDEVIATION", 4, "?"},
    {0xD94, "JUMPJET", 1, "?"},
    {0xD95, "CRASHABLE", 1, "?"},
    {0xD96, "CONSIDEREDAIRCRAFT", 1, "?"},
    {0xD97, "ORGANIC", 1, "?"},
    {0xD98, "NOSHADOW", 1, "?"},
    {0xD99, "CANPASSIVEAQUIRE", 1, "bool"},
    {0xD9A, "CANRETALIATE", 1, "bool"},
    {0xD9B, "REQUIRESSTOLENTHIRDTECH", 1, "bool"},
    {0xD9C, "REQUIRESSTOLENSOVIETTECH", 1, "bool"},
    {0xD9D, "REQUIRESSTOLENALLIEDTECH", 1, "bool"},
    {0xDA0, "REQUIREDHOUSES", 4, "?"},
    {0xDA4, "FORBIDDENHOUSES", 4, "?"},
    {0xDA8, "SECRETHOUSES", 4, "?"},
    {0xDAC, "USEBUFFER", 1, "?"},
    {0xDBC, "ISSELECTABLECOMBATANT", 1, "?"},
    {0xDBD, "ACCELERATES", 1, "?"},
    {0xDBE, "DISABLEVOXELCACHE", 1, "?"},
    {0xDBF, "DISABLESHADOWCACHE", 1, "?"},
    {0xDC4, "ZFUDGECOLUMN", 4, "?"},
    {0xDC8, "ZFUDGETUNNEL", 4, "?"},
    {0xDCC, "ZFUDGEBRIDGE", 4, "?"},
};
inline constexpr FieldName kFN_UnitTypeClass[] = {
    {0x67C, "SPEEDTYPE", 4, "?"},
    {0xDFC, "MOVEMENTRESTRICTEDTO", 4, "?"},
    {0xE0D, "CRATEGOODIE", 1, "bool"},
    {0xE0E, "HARVESTER", 1, "bool"},
    {0xE13, "ISSIMPLEDEPLOYER", 1, "bool"},
    {0xE14, "ISTILTER", 1, "bool"},
    {0xE16, "TOOBIGTOFITUNDERBRIDGE", 1, "bool"},
    {0xE1A, "CARRIESCRATE", 1, "bool"},
    {0xE5C, "WALKFRAMES", 1, "int"},
    {0xE5D, "FIRINGFRAMES", 1, "int"},
};

inline constexpr ClassFieldNames kFieldNames[] = {
    {"BuildingTypeClass", 168, kFN_BuildingTypeClass},
    {"InfantryTypeClass", 20, kFN_InfantryTypeClass},
    {"ObjectTypeClass", 15, kFN_ObjectTypeClass},
    {"TechnoTypeClass", 168, kFN_TechnoTypeClass},
    {"UnitTypeClass", 10, kFN_UnitTypeClass},
};

inline constexpr uint32_t kFieldNameClassCount =
    sizeof(kFieldNames) / sizeof(kFieldNames[0]);

/// 查 (类, 偏移) 的字段名 —— 也就是这个偏移是从哪个 INI 键读出来的。找不到返回 nullptr。
inline const char* FieldNameOf(const char* cls, uint32_t off) {
    if (cls == nullptr) return nullptr;
    for (uint32_t i = 0; i < kFieldNameClassCount; ++i) {
        if (kFieldNames[i].cls == nullptr || std::strcmp(kFieldNames[i].cls, cls) != 0)
            continue;
        for (uint32_t j = 0; j < kFieldNames[i].count; ++j)
            if (kFieldNames[i].fields[j].off == off) return kFieldNames[i].fields[j].key;
        return nullptr;
    }
    return nullptr;
}

}  // namespace re
}  // namespace ra2
